# Generated by Django 4.2.3 on 2023-08-05 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisment', '0004_advertisement_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата обновления'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата'),
        ),
    ]
