# Generated by Django 4.2.3 on 2023-08-05 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisment', '0005_advertisement_update_date_alter_advertisement_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'Список объявлений', 'verbose_name_plural': 'Список объявлений'},
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='update_date',
            new_name='updated_at',
        ),
    ]
