# Generated by Django 4.2.3 on 2023-08-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisment', '0008_alter_advertisement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default=0, upload_to='advertisment/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
